### ISSUE TITLE
requestAnimationFrame recursion on mobile

### ISSUE THREAD

**Issue by itsthisjustin** [mozilla/unity-webvr-export#127] opened 2018-02-12 22:14 UTC
As seen here: https://github.com/mozilla/unity-webvr-export/issues/54#issuecomment-363622646

I'm getting the same issue. Even the sample projects present this problem on all mobile browsers. I see on Firefox, Chrome (with flags for webvr set) and oddly enough on the Firefox nightly on Android tapping the headset icon just makes the experience full screen.

**Comment by cvan** [comment] 2018-02-13 01:53
Thanks for digging this up from the comment and filing an issue. I'm going to take a look at this.

**Comment by cvan** [comment] 2018-02-13 12:53
@itsthisjustin @caseyyee @delapuente: can you try checking out my branch in PR #132, and see it fixes things for you?

what are your steps to reproduce? just load https://mozilla.github.io/unity-webvr-export/ on one of your devices?

- Firefox for Android (Note 8)
- Chrome for Android (Note 8)
- Safari (iPhone X)

correct me if I'm missing something.

**Comment by cvan** [comment] 2018-02-13 18:27
Original source was commented in https://github.com/mozilla/unity-webvr-export/issues/54#issuecomment-363622646:

![image](https://user-images.githubusercontent.com/203725/36166786-709690f2-10a8-11e8-88b5-622a4be69635.png)

**Comment by itsthisjustin** [comment] 2018-02-13 19:04
<img width="1041" alt="5wvlu_ofecnvwmyj7mmebmzc91yylplg-xxrvdyjejhxixumm" src="https://user-images.githubusercontent.com/1875695/36167885-5df42d2a-10c5-11e8-8205-71f79f270b35.png">
On Firefox Stable the error still shows up in the console, however on both Chrome and Canary on Android, the experience doesn't crash anymore. It also now shows me the "VR Ready" icon which didn't previously show up.

**Comment by itsthisjustin** [comment] 2018-02-13 20:26
@caseyyee yeah I guess that's going to depend largely upon how WebGL and WebVR are "handled" moving forward. The main page of webvr touts Cardboard as it's baseline way to experience the technology. I feel like it should either say "Hey when building for mobile, experiences need to be downgraded an optimized." or there needs to be a flat out "unsupported" statement. In the case that this is a library for WebVR which touts cardboard compatibility, I would expect it to adhere to that. 

So if this Unity asset doesn't officially support mobile, it might not be good to say it's an export to webVR then since WebVR officially DOES support mobile.

**Comment by itsthisjustin** [comment] 2018-02-13 20:31
Update: iPhone X with Safari gives the error

**Comment by caseyyee** [comment] 2018-02-14 04:56
@itsthisjustin It's not actually a limitation of WebGL or WebVR.  Mobile devices unfortunately simply don't have the power or memory to run Unityplayer well.

**Comment by cvan** [comment] 2018-02-27 06:57
@caseyyee how should we go about updating the `webvr-polyfill` to include this patch (or the changes within this patch)? https://github.com/immersive-web/cardboard-vr-display/commit/6f6a0c1e8b28eb4a3c861aeab4f814e93207fb85

we don't want to upgrade the `webvr-polyfill` (#113) because of the changes required (#125).

and the `webvr-polyfill.min.js` is obviously minified. (this is going to get gross, heh, brb…)

**Comment by caseyyee** [comment] 2018-02-27 19:50
@cvan we're going to want to add basic controls first to navigate the scene.  Once that's in, the polyfill can go in:
https://github.com/mozilla/unity-webvr-export/issues/125

**Comment by caseyyee** [comment] 2018-02-27 19:53
@cvan probably just need to wait till we get fps controls in first.  I don't think we can do much otherwise we lose fallback controls.

**Comment by cvan** [comment] 2018-02-28 02:27
@caseyyee see the PR I opened yesterday: https://github.com/mozilla/unity-webvr-export/pull/175/files

**Comment by cvan** [comment] 2018-03-01 03:00
this is fixed by PR #175. @itsthisjustin: could you please try the version on `master` and let us know if it resolves your issue? thank you!

**Closed by cvan** 2018-03-01 03:00 UTC
Labels: bug
