### ISSUE TITLE
Black Line in the middle of the image

### ISSUE THREAD

**Issue by ferreXD** [mozilla/unity-webvr-export#278] opened 2018-05-08 10:58 UTC
Hello!

I'm getting a weird error, it happens when entering VR Mode. A black line appears in the middle of the image, as you can see in the image below.

Is there anyway I can fix this? 

![black_line_error](https://user-images.githubusercontent.com/39083343/39753331-b9951fb4-52be-11e8-9c42-ed1847584cc9.png)

Edit: 

Has it something to do with this quadruple view I'm getting on the headset?

![quadruple_view](https://user-images.githubusercontent.com/39083343/39753868-8f7cc7fc-52c0-11e8-9edf-fab452641702.png)

**Comment by caseyyee** [comment] 2018-05-08 22:02
Interesting!  Never ran into this issue before.  Looks like what's happening is the left/right cameras are being used rather than the mainCamera in-editor.

Was there anything specific you did here?  Or did you just straight-up open the project in Unity?

**Comment by caseyyee** [comment] 2018-05-08 22:04
Also, you shouldn't have to _Enter VR_ while in the editor.  Just pressing the _Play_ should work.   Have you tried pressing `v` (toggles VR) to see if it resolves the issue?

**Comment by delapuente** [comment] 2018-05-10 06:33
> As you said in the second post if don't toggle Enter VR in editor it works fine... but the reason I toggle it, it's in order to check if it is seen properly, because Enter VR mode is the way it would be seen in a website, isn't it?

Right and that's because for WebVR, we do need to split the screen. This is not needed by Unity which is able to take the current camera and convert it automatically in two identical virtual cameras, one per eye.

I'm closing this for now.

**Comment by caseyyee** [comment] 2018-05-14 00:06
As per @delapuente , you shouldn't have to _enter vr_ in Unity to simulate your scene.  It should just do this automatically for you.  You shouldn't be seeing the display issue though, so I filed issue to fix it  https://github.com/mozilla/unity-webvr-export/issues/282

**Comment by cvan** [comment] 2018-05-23 02:43
thanks for the useful STR. I was able to reproduce this.

**Comment by cvan** [comment] 2018-05-24 17:37
@caseyyee fixed this in PR #282, I reviewed it, and it's merged in `master` now, slated for the `v1.4.0` milestone.

**Closed by cvan** 2018-05-24 17:37 UTC
