### ISSUE TITLE
Must reboot machine in order for VR to work on second Unity launch

### ISSUE THREAD

**Issue by omgitsraven** [mozilla/unity-webvr-export#265] opened 2018-04-27 16:17 UTC
To reproduce:

1. Open a Unity project that uses this WebVR exporter. Hit the play button and see that VR works.
2. Quit Unity.
3. Open the same project again (relaunching Unity in the process). VR mode no longer works -- I just see the Oculus home space.
4. Reboot machine.
5. Open the same project again. VR mode works again (for now).

Please note, this is **specific** to projects that use this WebVR exporter -- Unity's native VR support does **not** cause this to happen, I can relaunch Unity as often as I want for projects where I've just ticked the "virtual reality supported" box.

I'm using Unity 2017.4, on Windows 10, with an Oculus Rift.

One detail that might help diagnosing -- after I've quit Unity, trying to close the Oculus window (the one where they try to sell you games) still tells me that it's going to interrupt something in progress, even though Unity was the only thing using it and (in theory) it is already shut down. Also, even after closing the Oculus window, my PC's fan continues spinning noisily (as though my computer were under heavy load) until I reboot. So clearly *something* isn't actually shutting down when Unity closes a project that uses this add-on.

**Comment by delapuente** [comment] 2018-05-10 07:16
I don't have an Oculus and this was not happening with my VIVE. Can you take a look? @cvan @caseyyee ?

**Comment by caseyyee** [comment] 2018-05-13 23:38
I haven't encountered any issues with using Oculus.  @omgitsraven, are you experiencing issues with the project in this repo?  Or are you importing the assets into an existing project?   Does it work when you export to WebVR and use it in the browser?  Thanks for filing the issue!

**Comment by omgitsraven** [comment] 2018-05-14 01:09
It's fine in the browser, this is just in the editor. I'm importing the WebVR exporter from the Asset Store and adding it to a new project. At that point, it happens the same whether I add a WebVRCameraSet to an empty scene, or whether I open the desert scene in WebVR/Scenes.

Also, while testing just now, I realised I'd been doing one step without thinking and didn't mention it, and it turns out to be the key to the whole thing, whoops... I also found a temporary workaround, but it doesn't always work.

So, here is the updated instructions for reproducing:
1. Open a Unity project that has the WebVR exporter. Hit the play button and see that VR works.
2. Quit Unity.
3. **Close the Oculus window** (the one where they try to sell you games). It will warn you that you're closing something in progress even though you've already shut down Unity. Confirm that you really want to close it.
4. Open the same project again, and hit play, and you'll only see the Oculus home space.

Step 3 is the new one; it turns out, if you leave the Oculus window hanging around in between, you can relaunch Unity as many times as you want. But it's a bit annoying to leave that window open all day (and it's normally not required by anything else).
At this point, to potentially buy yourself another relaunch:

5. Quit Unity and close the Oculus window.
6. Open Task Manager, and kill "VR Compositor", "VR Dashboard", and "VR Server".
7. Open the project again and VR will work.

However, sometimes it seems like the three VR processes won't come back, which means there's nothing to kill to get another shot? (It still stops working again if you close the Oculus window at any point, even if the three VR processes don't come back. At that point I'm stumped, and just have to reboot.)

**Comment by caseyyee** [comment] 2018-05-14 23:38
Ah interesting.   I always just leave the Oculus window open as i've observed that it wasn't always able to Enter VR reliably unless it was open.  I just assumed it was required to have it open for any VR application to function (similar to how Steam VR works).

One thing you could try is to go into the `Player settings > Download Tab > XR Settings` and try using Open VR rather than Oculus?  I will see if I can reproduce the issue.

Also, re killing processes.  I think that seems like it could cause more problems than it solves.  But I don't know how those processes function.  Could also be some kind of Oculus setting to disable the Home app altogether -- which would be nice.

**Comment by caseyyee** [comment] 2018-05-14 23:40
Found this,
Running the Oculus app as administrator makes it so that it doesn't start home:
https://forums.oculusvr.com/community/discussion/53317/how-to-prevent-home-from-starting-when-playing-steam-games

**Comment by omgitsraven** [comment] 2018-05-14 23:45
Oh wow, that's good to know, thanks!

I don't think that addresses the issue, though? Home is just what it brings up when there's nothing for it to show; I think it would just be replaced with the grey grid...

Having the Oculus window open *is* important for VR apps to function, but VR apps always open it automatically, is the thing. You have to leave it open as long as that app is running, but once you're done, you can close it, and it'll open itself again the next time it's needed.

And yeah, I don't think killing processes is a useful workaround, I just mentioned it in case it helps narrow down the problem.

I'll try the XR Settings change soon, thanks!

**Comment by caseyyee** [comment] 2018-05-15 01:17
@omgitsraven I tried all different combinations and I don't seem to be having this issue.
I tried the order in which you outlined, but also in other alternate orders as well (eg: closing oculus first while in Unity, etc).

The only other thing I can think of is that maybe your Unity and Oculus versions specifically could be having some issues.   I am currently testing with Unity 2018.1.0f2 (on Windows) and running Oculus in the Public Test Channel with Rift Core 2.0 Beta turned on (All in settings).  I realize this is a pretty bleeding edge config though.

![image](https://user-images.githubusercontent.com/1560884/40031118-1f283194-5829-11e8-92a1-5d99bb815c8b.png)

This is all running with the XR settings set to _Oculus_

**Comment by omgitsraven** [comment] 2018-05-17 16:51
OK, here's the funny twist—changing from OpenVR to Oculus int he XR Settings absolutely fixes this problem, but it also introduces a DIFFERENT problem where my head is way below the stage.

Should I just drop this thread now that we know this, and start a new one for the new issue?

(Just for context, I've been testing this in 2017.4.1f1, but it also happens to me in 2018.2; I'm in Rift Core 2.0 Beta, but not in Public Test Channel.)

**Comment by caseyyee** [comment] 2018-07-19 18:36
I've made a lot of updates with the 1.4 release that should have solved this issue and have tested both Open VR and Oculus XR settings, both seem to work.  Reopen if not, Thanks!

**Closed by caseyyee** 2018-07-19 18:36 UTC
Labels: bug

**Comment by omgitsraven** [comment] 2018-07-19 20:57
Hi, sorry, I thought I'd checked back in about this -- it is definitely still happening, BUT, in the meantime I've discovered that it also happens in any Unity VR project, even ones that don't include this WebVR plugin, so the issue never belonged here to begin with, so sorry about that.

**Comment by caseyyee** [comment] 2018-07-25 21:56
@omgitsraven I haven't been running into the issue at all.  I could be something specifically to do with your configuration?  Might be worth re-installing Steam, Oculus or even Unity since it could be in the XR feature?  Just for the record, what version of Unity, Steam and Oculus are you using?

**Comment by omgitsraven** [comment] 2018-07-25 22:21
I've uninstalled & reinstalled lots of copies of Unity over the last little while, so I doubt it's that. (I'm currently on 2018.2, but it was happening back on 2017.4 if I remember right.) I reinstalled SteamVR, and even Steam itself, and that didn't help.

At this point, I'm getting ready to build a new machine soon, and I think I'm just going to pray it doesn't happen on a system where everything is being installed for the first time, heh :)
